# .github/workflows/main.yml
name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      run: sudo apt-get install cmake -y

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cp input.txt build/input.txt
        cd build
        OUTPUT=$(./Addition)
        echo "$OUTPUT" | tee output.txt
        diff output.txt ../expected_output.txt
