name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      run: sudo apt-get install cmake -y

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: List build directory contents (debugging)
      run: ls -la build

    - name: Run tests
      run: |
        cd build
        echo "3 5" | ./Addition > output.txt
        cat output.txt # Add this line to see the actual output in the workflow logs
        echo "Enter two numbers: The sum is: 8" > expected_output.txt # Update this line if you modified the `1.cpp` file
        diff output.txt expected_output.txt
